## NumPy

In [1]:
# !pip install numpy

In [2]:
import numpy as np

### np.array() 

In [3]:
l = [1, 2, 3, 4, 5]

In [5]:
npa = np.array(l)

In [6]:
type(l), type(npa)

(list, numpy.ndarray)

In [7]:
npa.shape

(5,)

In [11]:
l.append('string')

In [12]:
npa = np.array(l)

In [13]:
npa

array(['1', '2', '3', '4', '5', '6', 'string'], dtype='<U11')

In [15]:
l1 = [1, 4, 9, 16]

In [16]:
l

[1, 2, 3, 4, 5, 6, 'string']

In [17]:
l + l1

[1, 2, 3, 4, 5, 6, 'string', 1, 4, 9, 16]

In [18]:
np.array(l + l1)

array(['1', '2', '3', '4', '5', '6', 'string', '1', '4', '9', '16'],
      dtype='<U11')

In [21]:
l + [20]

[1, 2, 3, 4, 5, 6, 'string', 20]

In [22]:
l = [[1, 2], [3, 4], [3, 4]]

In [23]:
npa2d = np.array(l)

In [24]:
npa2d

array([[1, 2],
       [3, 4],
       [3, 4]])

In [25]:
npa2d.shape

(3, 2)

In [26]:
npa2d = np.array(l, dtype = 'float')

In [27]:
npa2d

array([[1., 2.],
       [3., 4.],
       [3., 4.]])

In [28]:
npa2d.astype('int')

array([[1, 2],
       [3, 4],
       [3, 4]])

In [32]:
npa2d = npa2d.astype('str')

In [35]:
npa2d[0][0] + str(1)

'1.01'

### `np.nan` and `np.inf` 

In [37]:
np.nan == np.nan

False

In [38]:
None == None

True

In [39]:
np.inf == np.inf

True

In [48]:
npa2d = npa2d.astype('float')

In [50]:
npa2d = npa2d.astype('int')

In [51]:
npa2d

array([[1, 2],
       [3, 4],
       [3, 4]])

In [53]:
npa2d = npa2d.astype('float')

In [54]:
npa2d[0][0] = np.nan
npa2d[1][1] = np.inf

In [55]:
npa2d

array([[nan,  2.],
       [ 3., inf],
       [ 3.,  4.]])

In [57]:
np.isnan(npa2d)

array([[ True, False],
       [False, False],
       [False, False]])

In [58]:
np.isinf(npa2d)

array([[False, False],
       [False,  True],
       [False, False]])

In [59]:
flag = np.isnan(npa2d) | np.isinf(npa2d)

In [60]:
flag

array([[ True, False],
       [False,  True],
       [False, False]])

In [61]:
npa2d[flag]

array([nan, inf])

In [62]:
npa2d[flag] = 0

In [63]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

### Statistical Operations 

In [64]:
# mean, var, std, med

In [65]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [66]:
npa2d.mean()

2.0

In [67]:
npa2d.min()

0.0

In [68]:
npa2d.max()

4.0

In [69]:
npa2d.var()

2.3333333333333335

In [70]:
npa2d.std()

1.5275252316519468

In [72]:
np.median(npa2d)

2.5

### Shape(), Reshape(), Ravel() 

In [73]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [74]:
npa2d.shape

(3, 2)

In [75]:
npa2d.reshape(2, 3)

array([[0., 2., 3.],
       [0., 3., 4.]])

In [77]:
npa2d.reshape(1, 6)

array([[0., 2., 3., 0., 3., 4.]])

In [78]:
npa2d.reshape(1, 6).ravel()

array([0., 2., 3., 0., 3., 4.])

In [79]:
npa2d.flatten()

array([0., 2., 3., 0., 3., 4.])

### sequence, repetitions, and random numbers

#### arange(), linspace(), random(), zeros(), and ones() 

In [81]:
np.arange(1, 5, dtype = 'float')

array([1., 2., 3., 4.])

In [82]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [84]:
np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [85]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [86]:
np.zeros([1, 5])

array([[0., 0., 0., 0., 0.]])

In [87]:
np.zeros([1, 2, 3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [90]:
np.ones([1, 2])

array([[1., 1.]])

In [91]:
np.tile([1, 2], 3)

array([1, 2, 1, 2, 1, 2])

In [92]:
np.repeat([1, 2], 3)

array([1, 1, 1, 2, 2, 2])

In [93]:
np.random.rand(3, 3)

array([[0.0473649 , 0.94277306, 0.44060066],
       [0.78947139, 0.15280511, 0.73514322],
       [0.93069794, 0.90676865, 0.88022416]])

In [101]:
np.random.randint(0, 100, [3, 3])

array([[62, 35, 20],
       [15, 44, 90],
       [10, 82, 68]])

In [146]:
np.random.seed(1)
np.random.randint(0, 100, [3, 3])

array([[37, 12, 72],
       [ 9, 75,  5],
       [79, 64, 16]])

In [154]:
np.random.randint(0, 100, [3, 3])

array([[ 9, 67, 23],
       [27, 37, 57],
       [83, 38,  8]])

In [155]:
np.unique(npa2d)

array([0., 2., 3., 4.])

In [156]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [157]:
np.unique(npa2d, return_counts= True)

(array([0., 2., 3., 4.]), array([2, 1, 2, 1], dtype=int64))

### Where()

In [158]:
arr = np.array([8,94,8,56,1,3,4,5,7])

In [159]:
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [160]:
np.where(arr>10)

(array([1, 3], dtype=int64),)

In [161]:
index = np.where(arr>10)
arr[index]

array([94, 56])

In [162]:
index = np.where(arr<10)
arr[index]

array([8, 8, 1, 3, 4, 5, 7])

In [164]:
index = np.where(arr==10)
arr[index]

array([], dtype=int32)

In [165]:
arr>10

array([False,  True, False,  True, False, False, False, False, False])

In [166]:
arr[arr>10]

array([94, 56])

In [167]:
arr.max()

94

In [168]:
arr.argmax()

1

In [169]:
arr.argmin()

4

In [170]:
arr[arr.argmin()]

1

### File Read and Write 

In [171]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [172]:
np.savetxt('npa2d.csv', npa2d, delimiter=',')

In [174]:
np.loadtxt('npa2d.csv', delimiter=',')

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [175]:
np.save('data.npy', npa2d)

In [176]:
np.load('data.npy')

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [178]:
np.savez('both.npz', arr, npa2d)

In [181]:
d = np.load('both.npz')

In [183]:
d.files

['arr_0', 'arr_1']

In [185]:
d[d.files[1]]

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

### Concatenate and Sorting 

In [186]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [187]:
np.concatenate([npa2d, npa2d], axis = 0)

array([[0., 2.],
       [3., 0.],
       [3., 4.],
       [0., 2.],
       [3., 0.],
       [3., 4.]])

In [188]:
np.concatenate([npa2d, npa2d], axis = 1)

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [3., 4., 3., 4.]])

In [189]:
np.concatenate([npa2d, arr], axis = 1)

ValueError: all the input arrays must have same number of dimensions

In [190]:
np.vstack([npa2d, npa2d])

array([[0., 2.],
       [3., 0.],
       [3., 4.],
       [0., 2.],
       [3., 0.],
       [3., 4.]])

In [202]:
npa = np.hstack([npa2d, npa2d])

In [203]:
npa

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [3., 4., 3., 4.]])

In [194]:
npa.sort()

In [195]:
npa

array([[0., 0., 2., 2.],
       [0., 0., 3., 3.],
       [3., 3., 4., 4.]])

In [204]:
npa.sort(axis = 1)
npa

array([[0., 0., 2., 2.],
       [0., 0., 3., 3.],
       [3., 3., 4., 4.]])

### Working with Dates 

In [206]:
d = np.datetime64('2020-12-01 23:34:23')

In [208]:
d

numpy.datetime64('2020-12-01T23:34:23')

In [209]:
d + 10

numpy.datetime64('2020-12-01T23:34:33')

In [210]:
oneday = np.timedelta64(1, 'D')

In [211]:
oneday

numpy.timedelta64(1,'D')

In [212]:
d + oneday

numpy.datetime64('2020-12-02T23:34:23')

In [213]:
oneminute = np.timedelta64(1, 'm')

In [214]:
d + oneminute

numpy.datetime64('2020-12-01T23:35:23')